---
- name: vmware test
  hosts: localhost
  tasks:
    - name: Create a snapshot
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter_name }}"
        folder: "/{{ datacenter_name }}/vm/"
        name: "{{ guest_name }}"
        state: present
        snapshot_name: "{{ snapshot_name }}"
        description: "{{ snap1_description }}"
      delegate_to: localhost
      